version: '3.8'

services:
  energymeter:
    container_name: energymeter
    image: slothcroissant/rpi-energymeter:nightly
    restart: always
    network_mode: host
    environment:
      - ct0_0=100
      - ct0_1=100
      - ct0_2=30
      - ct0_3=30
      - ct0_4=20
      - ct0_5=20
      - ct0_6=20
      - ct0_7=20
      - ct1_0=20
      - ct1_1=20
      - ct1_2=20
      - ct1_3=20
      - ct1_4=20
      - ct1_5=20
      - ct1_6=30
      - ct1_7=20
    devices:
      - /dev/spidev0.0
    privileged: true