name: Docker Image CI

on:
  push:
    branches: [ nightly ]

env:
  DOCKER_USERNAME: slothcroissant
  DOCKER_CONTAINER_NAME: rpi-energymeter
  DOCKER_TARGET_PLATFORM: linux/arm/v7

jobs:
  changed_files:
    runs-on: ubuntu-latest
    outputs:
      readme : ${{ steps.filter.outputs.readme }}
      src : ${{ steps.filter.outputs.src }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          readme:
            - 'README.md'
          src:
            - 'src/**'
            - 'Dockerfile'
        list-files: json
        base: 'nightly'

  build_and_push:
    needs: changed_files
    if: ${{ needs.changed_files.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Prepare
      if: success()
      id: prepare
      run: |
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
        echo ::set-output name=tag::$(date +%Y.%m.%d-$GITHUB_RUN_NUMBER)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build container and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: ${{ steps.prepare.outputs.docker_platform }}
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:${{ steps.prepare.outputs.tag }}
          ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:nightly
          ghcr.io/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:${{ steps.prepare.outputs.tag }}
          ghcr.io/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:nightly

  dockerhub_metadata_update:
    runs-on: ubuntu-latest
    needs: changed_files
    if: ${{ needs.changed_files.outputs.readme == 'true' }}
    steps:
    - uses: actions/checkout@v3
    - name: Update Docker Hub Description & README
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}
        short-description: ${{ github.event.repository.description }}
